// @ts-nocheck -- skip type checking
import * as docs_9 from "../content/docs/terms.mdx?collection=docs&hash=1745640036427"
import * as docs_8 from "../content/docs/techstack.mdx?collection=docs&hash=1745640036427"
import * as docs_7 from "../content/docs/stripe.mdx?collection=docs&hash=1745640036427"
import * as docs_6 from "../content/docs/privacy.mdx?collection=docs&hash=1745640036427"
import * as docs_5 from "../content/docs/index.zh.mdx?collection=docs&hash=1745640036427"
import * as docs_4 from "../content/docs/index.mdx?collection=docs&hash=1745640036427"
import * as docs_3 from "../content/docs/env.mdx?collection=docs&hash=1745640036427"
import * as docs_2 from "../content/docs/docs.mdx?collection=docs&hash=1745640036427"
import * as docs_1 from "../content/docs/clerk.mdx?collection=docs&hash=1745640036427"
import * as docs_0 from "../content/docs/about.mdx?collection=docs&hash=1745640036427"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"about.mdx","absolutePath":"/Users/shankai/codebase/kong0/nexttool/content/docs/about.mdx"}, data: docs_0 }, { info: {"path":"clerk.mdx","absolutePath":"/Users/shankai/codebase/kong0/nexttool/content/docs/clerk.mdx"}, data: docs_1 }, { info: {"path":"docs.mdx","absolutePath":"/Users/shankai/codebase/kong0/nexttool/content/docs/docs.mdx"}, data: docs_2 }, { info: {"path":"env.mdx","absolutePath":"/Users/shankai/codebase/kong0/nexttool/content/docs/env.mdx"}, data: docs_3 }, { info: {"path":"index.mdx","absolutePath":"/Users/shankai/codebase/kong0/nexttool/content/docs/index.mdx"}, data: docs_4 }, { info: {"path":"index.zh.mdx","absolutePath":"/Users/shankai/codebase/kong0/nexttool/content/docs/index.zh.mdx"}, data: docs_5 }, { info: {"path":"privacy.mdx","absolutePath":"/Users/shankai/codebase/kong0/nexttool/content/docs/privacy.mdx"}, data: docs_6 }, { info: {"path":"stripe.mdx","absolutePath":"/Users/shankai/codebase/kong0/nexttool/content/docs/stripe.mdx"}, data: docs_7 }, { info: {"path":"techstack.mdx","absolutePath":"/Users/shankai/codebase/kong0/nexttool/content/docs/techstack.mdx"}, data: docs_8 }, { info: {"path":"terms.mdx","absolutePath":"/Users/shankai/codebase/kong0/nexttool/content/docs/terms.mdx"}, data: docs_9 }], [{"info":{"path":"meta.json","absolutePath":"/Users/shankai/codebase/kong0/nexttool/content/docs/meta.json"},"data":{"title":"Framework","pages":["---Introduction---","index","techstack","---Settings---","env","clerk","stripe","docs","---Legal---","privacy","terms","about"],"description":"The docs framework","root":true,"icon":"Building2"}}])